pfsense_virtualized: true
pfsense_interfaces: []
firewall_setup_pfsense_dns_addresses:
  - 1.1.1.1
  - 1.0.0.1
firewall_setup_pfsense_dns_hostnames:
  - cloudflare-dns.com
  - cloudflare-dns.com
firewall_setup_pfsense_dnslocalhost: local
firewall_setup_pfsense_users: []
firewall_setup_pfsense_timeservers:
  - 0.europe.pool.ntp.org
  - 1.europe.pool.ntp.org
  - 2.europe.pool.ntp.org
  - 3.europe.pool.ntp.org
