- name: dns | Ensure domain conf file exists
  ansible.builtin.file:
    path: "/etc/dnsmasq.d/{{ nat_management_domain }}.conf"
    state: touch
  become: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['core_dns'] }}"

- name: dns | Add static dns entry
  ansible.builtin.lineinfile:
    path: "/etc/dnsmasq.d/{{ nat_management_domain }}.conf"
    line: "address=/{{ inventory_hostname }}/{{ nat_management_nat_ip }}"
  become: true
  register: _result_dns
  delegate_to: "{{ item }}"
  loop: "{{ groups['core_dns'] }}"

- name: dns | Add ptr record
  ansible.builtin.lineinfile:
    path: "/etc/dnsmasq.d/{{ nat_management_domain }}.conf"
    line: "ptr-record={{ nat_management_nat_ip | ansible.utils.ipaddr('revdns') }},{{ inventory_hostname }}"
  become: true
  register: _result_dns_ptr
  delegate_to: "{{ item }}"
  loop: "{{ groups['core_dns'] }}"

- name: dns | Add static dns entries for domain (ldap)
  ansible.builtin.lineinfile:
    path: "/etc/dnsmasq.d/{{ nat_management_domain }}.conf"
    line: "srv-host=_ldap._tcp.dc._msdcs.{{ nat_management_domain }}, {{ nat_management_dc_ip }}"
  become: true
  register: _result_dns_ldap
  delegate_to: "{{ item }}"
  loop: "{{ groups['core_dns'] }}"
  when: nat_management_dc_ip is defined

- name: dns | Add static dns entries for domain (kerberos)
  ansible.builtin.lineinfile:
    path: "/etc/dnsmasq.d/{{ nat_management_domain }}.conf"
    line: "srv-host=_kerberos._tcp.dc._msdcs.{{ nat_management_domain }}, {{ nat_management_dc_ip }}"
  become: true
  register: _result_dns_kerberos
  delegate_to: "{{ item }}"
  loop: "{{ groups['core_dns'] }}"
  when: nat_management_dc_ip is defined

- name: dns | Add static dns entries for domain (ldap)
  ansible.builtin.lineinfile:
    path: "/etc/dnsmasq.d/{{ nat_management_domain }}.conf"
    line: "srv-host=_ldap._tcp.Default-First-Site-Name._sites.dc._msdcs.{{ nat_management_domain }}, {{ nat_management_dc_ip }}"
  become: true
  register: _result_dns_ldap2
  delegate_to: "{{ item }}"
  loop: "{{ groups['core_dns'] }}"
  when: nat_management_dc_ip is defined

- name: dns | Add static dns entries for domain (ldap)
  ansible.builtin.lineinfile:
    path: "/etc/dnsmasq.d/{{ nat_management_domain }}.conf"
    line: "srv-host=_ldap._tcp.ForestDnsZones.{{ nat_management_domain }}, {{ nat_management_dc_ip }}"
  become: true
  register: _result_dns_ldap3
  delegate_to: "{{ item }}"
  loop: "{{ groups['core_dns'] }}"
  when: nat_management_dc_ip is defined

- name: dns | Add static dns entries for domain (ldap)
  ansible.builtin.lineinfile:
    path: "/etc/dnsmasq.d/{{ nat_management_domain }}.conf"
    line: "srv-host=_ldap._tcp.{{ nat_management_domain }}, {{ nat_management_dc_ip }}"
  become: true
  register: _result_dns_ldap4
  delegate_to: "{{ item }}"
  loop: "{{ groups['core_dns'] }}"
  when: nat_management_dc_ip is defined

- name: dns | Add static dns entries for domain (ldap)
  ansible.builtin.lineinfile:
    path: "/etc/dnsmasq.d/{{ nat_management_domain }}.conf"
    line: "srv-host=_ldap._tcp.pdc._msdcs.{{ nat_management_domain }}, {{ nat_management_dc_ip }}"
  become: true
  register: _result_dns_ldap5
  delegate_to: "{{ item }}"
  loop: "{{ groups['core_dns'] }}"
  when: nat_management_dc_ip is defined

- name: dns | Add static dns entries for domain 2 (ldap)
  ansible.builtin.lineinfile:
    path: "/etc/dnsmasq.d/{{ nat_management_domain }}.conf"
    line: "srv-host=_ldap._tcp.Default-First-Site-Name._sites.{{ nat_management_domain }}, {{ nat_management_dc_ip }}"
  become: true
  register: _result_dns_ldap6
  delegate_to: "{{ item }}"
  loop: "{{ groups['core_dns'] }}"
  when: nat_management_dc_ip is defined

- name: dns | Restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
  when: _result_dns.changed or _result_dns_ldap.changed or _result_dns_kerberos.changed or _result_dns_ldap2.changed or _result_dns_ldap3.changed or _result_dns_ldap4.changed or _result_dns_ldap5.changed or result_dns_ldap5.changed or _result_dns_ptr.changed
  become: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['core_dns'] }}"
