galaxy_info:
  author: hack3d
  description: Configure cisco switch
  company: IT4smart GmbH
  license: "license (GPL v3)"
  min_ansible_version: "2.13"

dependencies:
  - name: cisco.ios
    version: 3.3.1