# code: language=ansible
- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - pfSense-pkg-sudo
    - pfSense-pkg-openvpn-client-export
    - pfSense-pkg-RRD_Summary

- name: Install VMWare package
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - pfSense-pkg-Open-VM-Tools
  when:
    - pfsense_virtualized
    - ansible_facts['chassis_vendor'] != "QEMU"

- name: Configure QEMU guest agent
  block:
    - name: Install QEMU guest agent package
      ansible.builtin.package:
        name: qemu-guest-agent
        state: present

    - name: Configure QEMU guest agent
      ansible.builtin.template:
        src: rc_conf_local.j2
        dest: /etc/rc.conf.local

    - name: Enable QEMU guest agent
      ansible.builtin.service:
        name: qemu-guest-agent
        enabled: true
        state: started
  when:
    - pfsense_virtualized
    - ansible_facts['chassis_vendor'] == "QEMU"

- name: Timezone and language
  pfsensible.core.pfsense_setup:
    timezone: Europe/Berlin
    language: de_DE

- name: Setup hostname and domain
  pfsensible.core.pfsense_setup:
    hostname: "{{ inventory_hostname_short }}"
    domain: "{{ domain_name }}"

- name: Convert list of dns servers to string
  ansible.builtin.set_fact:
    _dns_addresses: "{{ firewall_setup_pfsense_dns_addresses | join(' ') }}"
  when: firewall_setup_pfsense_dns_addresses | length > 0

- name: Convert list of dns hostnames to string
  ansible.builtin.set_fact:
    _dns_hostnames: "{{ firewall_setup_pfsense_dns_hostnames | join(' ') }}"
  when: firewall_setup_pfsense_dns_hostnames | length > 0

- name: Setup dns upstream
  pfsensible.core.pfsense_setup:
    dnsallowoverride: false
    dns_addresses: "{{ _dns_addresses }}"
    dns_hostnames: "{{ _dns_hostnames }}"
    dnslocalhost: "{{ firewall_setup_pfsense_dnslocalhost }}"

- name: Setup timeservers
  pfsensible.core.pfsense_setup:
    timeservers: 0.europe.pool.ntp.org 1.europe.pool.ntp.org 2.europe.pool.ntp.org 3.europe.pool.ntp.org

- name: Create IT4smart vpn user
  pfsensible.core.pfsense_user:
    name: it4smart
    password: "{{ vault_it4smart_fwl_password | password_hash('bcrypt') }}"

- name: Create user certificate
  pfsensible.core.pfsense_cert:
    method: internal
    name: "it4smart"
    ca: "OpenVPN CA"
    certtype: user
    keylen: 4096
    dn_country: DE

- name: Network
  ansible.builtin.include_tasks: network.yml
