- name: override | Debug remote network
  ansible.builtin.debug:
    msg: "OpenVPN Server Remote network: {{ _remote_network }}"
  when: firewall_openvpn_pfsense_server_mode == "p2p_tls"

- name: override |Convert list of remote networks to string comma separated
  ansible.builtin.set_fact:
    _remote_network_override: "{{ item.remote_network | join(', ') }}"
  when:
    - item.remote_network | length > 0
    - firewall_openvpn_pfsense_server_mode == "p2p_tls"


- name: override | Configure OpenVPN client override
  pfsensible.core.pfsense_openvpn_override:
    name: "{{ item.name }}"
    server_list: "{{ item.server_list }}"
    descr: "{{ item.description | default(omit) }}"
    local_network: "{{ _local_network | default(omit) }}"
    local_networkv6: "{{ _local_networkv6 | default(omit) }}"
    remote_network: "{{ _remote_network_override | default(omit) }}"
    remote_networkv6: "{{ _remote_networkv6 | default(omit) }}"
  become: true
  when: firewall_openvpn_pfsense_server_mode == "p2p_tls"
