- name: auth | Configure ldap authentication server
  pfsensible.core.pfsense_authserver_ldap:
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    port: "{{ item.port | default('389') }}"
    transport: "{{ item.transport | default(omit) }}"
    ca: "{{ item.ca | default(omit) }}"
    protver: "{{ item.protver | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    scope: "{{ item.scope | default(omit) }}"
    basedn: "{{ item.basedn | default(omit) }}"
    authcn: "{{ item.authcn | default(omit) }}"
    extended_enabled: "{{ item.extended_enabled | default(omit) }}"
    extended_query: "{{ item.extended_query | default(omit) }}"
    binddn: "{{ item.binddn | default(omit) }}"
    bindpw: "{{ item.bind_password | default(omit) }}"
    attr_user: "{{ item.attr_user | default(omit) }}"
    attr_group: "{{ item.attr_group | default(omit) }}"
    attr_member: "{{ item.attr_member | default(omit) }}"
    attr_groupobj: "{{ item.attr_groupobj | default(omit) }}"
    ldap_rfc2307: "{{ item.ldap_rfc2307 | default(omit) }}"
    ldap_rfc2307_userdn: "{{ item.ldap_rfc2307_userdn | default(omit) }}"
    ldap_utf8: "{{ item.ldap_utf8 | default(omit) }}"
    ldap_nostrip_at: "{{ item.ldap_nostrip_at | default(omit) }}"
    ldap_pam_groupdn: "{{ item.ldap_pam_groupdn | default(omit) }}"
    ldap_allow_unauthenticated: "{{ item.ldap_allow_unauthenticated | default(omit) }}"
  become: true
  when: item.type == 'ldap'
