# code: language=ansible
- name: Build one firewall rule dictionary
  ansible.builtin.set_fact:
    _firewall_rules: "{{ firewall_configuration_pfsense_firewall_rules | community.general.lists_mergeby(firewall_configuration_pfsense_custom_firewall_rules, \
                      'name') }}"

- name: Configure firewall rules
  ansible.builtin.include_tasks: firewall.yml
  with_items: "{{ _firewall_rules }}"

- name: Manage user on  PfSense
  ansible.builtin.include_tasks: user.yml
  with_items: "{{ openvpn_users }}"

- name: Manage dns resolver
  ansible.builtin.include_tasks: dns.yml

- name: Manage dhcp server
  ansible.builtin.include_tasks: dhcp_server.yml
  with_items: "{{ pfsense_interfaces }}"

- name: Manage dhcp static entries
  ansible.builtin.include_tasks: dhcp_static.yml
  when: pfsense_dhcp_static_enabled

- name: Manage dnat
  ansible.builtin.include_tasks: nat.yml

- name: Install additional packages
  ansible.builtin.include_tasks: package.yml

- name: Configure OpenVPN client
  ansible.builtin.include_tasks: openvpn_client.yml
  loop: "{{ firewall_configuration_pfsense_openvpn_client }}"

- name: Configure OpenVPN client override
  ansible.builtin.include_tasks:
    file: openvpn_client_override.yml
  loop: "{{ firewall_configuration_pfsense_openvpn_client_override }}"

- name: Configure static routes
  ansible.builtin.include_tasks: route.yml
  loop: "{{ firewall_configuration_pfsense_static_routes }}"

- name: Configure authentification server
  ansible.builtin.include_tasks: auth.yml
  loop: "{{ firewall_configuration_pfsense_authentication_server }}"
