# code: language=ansible
- name: Build one firewall rule dictionary
  ansible.builtin.set_fact:
    _firewall_rules: "{{ firewall_configuration_pfsense_firewall_rules | community.general.lists_mergeby(firewall_configuration_pfsense_custom_firewall_rules, \
                      'name') }}"

- name: Configure firewall rules
  ansible.builtin.include_tasks: firewall.yml
  with_items: "{{ _firewall_rules }}"

- name: Manage user on  PfSense
  ansible.builtin.include_tasks: user.yml
  with_items: "{{ openvpn_users }}"

- name: Manage dns resolver
  ansible.builtin.include_tasks: dns.yml

- name: Manage dhcp static entries
  ansible.builtin.include_tasks: dhcp_static.yml
  when: pfsense_dhcp_static_enabled

- name: Manage dnat
  ansible.builtin.include_tasks: nat.yml
