- name: openvpn_client | Import OpenVPN CA
  pfsensible.core.pfsense_ca:
    name: "{{ item.ca_name }}"
    method: existing
    certificate: "{{ item.ca }}"
  become: true
  loop: "{{ firewall_configuration_pfsense_openvpn_client }}"
  when: item.ca is defined

- name: openvpn_client | Import OpenVPN certificate
  pfsensible.core.pfsense_cert:
    name: "{{ item.cert_name }}"
    method: existing
    certificate: "{{ item.cert }}"
  become: true
  loop: "{{ firewall_configuration_pfsense_openvpn_client }}"
  when: item.cert is defined

- name: openvpn_client | Configure OpenVPN client
  pfsensible.core.pfsense_openvpn_client:
    name: "{{ item.name }}"
    mode: "{{ item.mode }}"
    authmode: "{{ item.authmode | default(omit) }}"
    disable: "{{ item.disable }}"
    interface: "{{ item.interface | default('wan') }}"
    server_addr: "{{ item.server_address }}"
    server_port: "{{ item.server_port }}"
    protocol: "{{ item.protocol }}"
    dev_mode: "{{ item.dev_mode }}"
    tls: "{{ item.tls | default(omit) }}"
    tls_type: "{{ item.tls_type | default('auth') }}"
    ca: "{{ item.ca_name | default(omit) }}"
    crl: "{{ item.crl | default(omit) }}"
    cert: "{{ item.cert_name | default(omit) }}"
    cert_depth: "{{ item.cert_depth | default(1) }}"
    strictusercn: "{{ item.strictusercn | default(true) }}"
    shared_key: "{{ item.shared_key | default(omit) }}"
    dh_length: "{{ item.dh_length | default(4096) }}"
    ecdh_curve: "{{ item.ecdh_curve }}"
    data_ciphers_fallback: "{{ item.data_ciphers_fallback }}"
    data_ciphers: "{{ item.data_ciphers }}"
    ncp_enable: "{{ item.ncp_enable | default(false) }}"
    digest: "{{ item.digest }}"
    tunnel_network: "{{ item.tunnel_network | default(omit) }}"
    tunnel_networkv6: "{{ item.tunnel_networkv6 | default(omit) }}"
    remote_network: "{{ item.remote_network }}"
    remote_networkv6: "{{ item.remote_networkv6 | default(omit) }}"
    gwredir: "{{ item.gwredir | default(false) }}"
    gwredir6: "{{ item.gwredir6 | default(false) }}"
    maxclients: "{{ item.maxclients | default(omit) }}"
    compression: "{{ item.compression | default(omit) }}"
    compression_push: "{{ item.compression_push | default(omit) }}"
    passtos: "{{ item.passtos | default(omit) }}"
    client2client: "{{ item.client2client | default(omit) }}"
    dynamic_ip: "{{ item.dynamic_ip | default(omit) }}"
    topology: "{{ item.topology | default(omit) }}"
    dns_domain: "{{ item.dns_domain }}"
    dns_client1: "{{ item.dns_client1 }}"
    dns_client2: "{{ item.dns_client2 | default(omit) }}"
    dns_client3: "{{ item.dns_client3 | default(omit) }}"
    dns_client4: "{{ item.dns_client4 | default(omit) }}"
    push_register_dns: "{{ item.push_register_dns | default(omit) }}"
    create_gw: "{{ item.create_gw }}"
    verbosity_level: "{{ item.verbosity_level | default(omit) }}"
    custom_options: "{{ item.custom_options | default(omit) }}"
  become: true
  loop: "{{ firewall_configuration_pfsense_openvpn_client }}"
