- name: Configure OpenVPN client
  pfsensible.core.pfsense_openvpn_client:
    name: "{{ item.name }}"
    mode: "{{ item.mode }}"
    authmode: "{{ item.authmode | default(omit) }}"
    disable: "{{ item.disable }}"
    interface: "{{ item.interface | default(wan) }}"
    server_addr: "{{ item.server_address }}"
    server_port: "{{ item.server_port }}"
    protocol: "{{ item.protocol }}"
    dev_mode: "{{ item.dev_mode }}"
    tls: "{{ item.tls | default(omit) }}"
    tls_type: "{{ item.tls_type | default(auth) }}"
    ca: "{{ item.ca }}"
    crl: "{{ item.crl | default(omit) }}"
    cert: "{{ item.cert }}"
    cert_depth: "{{ item.cert_depth | default(1) }}"
    strictusercn: "{{ item.strictusercn | default(true) }}"
    shared_key: "{{ item.shared_key }}"
    dh_length: "{{ item.dh_length | default(4096) }}"
    ecdh_curve: "{{ item.ecdh_curve }}"
    data_ciphers_fallback: "{{ item.data_ciphers_fallback }}"
    data_ciphers: "{{ itemm.data_ciphers }}"
    ncp_enable: "{{ item.ncp_enable | default(false) }}"
    digest: "{{ item.digest }}"
    tunnel_network: "{{ item.tunnel_network }}"
    tunnel_networkv6: "{{ item.tunnel_networkv6 | default(omit) }}"
    remote_network: "{{ item.remote_network }}"
    remote_networkv6: "{{ item.remote_networkv6 | default(omit) }}"
    gwredir: "{{ item.gwredir | default(false) }}"
    gwredir6: "{{ item.gwredir6 | default(false) }}"
    maxclients: "{{ item.maxclients | default(omit) }}"
    compression: "{{ item.compression }}"
    compression_push: "{{ item.compression_push }}"
    passtos: "{{ item.passtos }}"
    client2client: "{{ item.client2client }}"
    dynamic_ip: "{{ item.dynamic_ip }}"
    topology: "{{ item.topology }}"
    dns_domain: "{{ item.dns_domain }}"
    dns_client1: "{{ item.dns_client1 }}"
    dns_client2: "{{ item.dns_client2 }}"
    dns_client3: "{{ item.dns_client3 }}"
    dns_client4: "{{ item.dns_client4 }}"
    push_register_dns: "{{ item.push_register_dns }}"
    create_gw: "{{ item.create_gw }}"
    verbosity_level: "{{ item.verbosity_level }}"
    custom_options: "{{ item.custom_options | default(omit) }}"
  loop: "{{ firewall_configuration_pfsense_openvpn_client }}"
