# code: language=ansible
- name: "user | Manage user {{ item.username }}"
  pfsensible.core.pfsense_user:
    name: "{{ item.username }}"
    password: "{{ item.password | password_hash('bcrypt') }}"
  become: true

- name: user | Create user certificate
  pfsensible.core.pfsense_cert:
    method: internal
    name: "{{ item.username }}"
    ca: "{{ item.ca }}"
    certtype: user
    keylen: "{{ item.keylen }}"
    dn_country: "{{ item.dn_country }}"
    lifetime: "{{ item.lifetime }}"
  become: true
